version: '3'
services:
  producer:
    build: producer
    depends_on:
      - rmq0
  consumer:
    build: consumer
    depends_on:
      - rmq1
  crl:
    build: crl
    hostname: crl-server
    # Note: handy for debugging
    # ports:
    #   # HOST:CONTAINER
    #   - 8000:8000
  rmq0:
    build: rmq0
    hostname: rmq0
    ports:
      # HOST:CONTAINER
      - 15672:15672
  rmq1:
    build: rmq1
    hostname: rmq1
    ports:
      # HOST:CONTAINER
      - 15673:15672
